[package]
name = "mmoldb"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
rocket_db_pools = { version = "0.2.0", features = ["diesel_postgres"] }
diesel = "2.1.1"
diesel_migrations = "2.1.0"
chrono = { version = "0.4.40", features = ["serde"] }
thiserror = "2.0.12"