volumes:
  postgres-data:

secrets:
  db_admin_password:
    file: .db_admin_password

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    secrets:
      - db_admin_password
    env_file:
        - .env-prod
    ports:
      - "42424:42424"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - db_admin_password
    env_file:
        # Ensure that the variables in .env-prod match the same variables in devcontainer.json
        - .env-prod
