[default]
port = 42424  # Must match the port forwarded in .devcontainer/devcontainer.json

[default.databases.mmoldb]
url = "postgres://postgres:postgres@db/mmoldb"
max_connections = 20  # deadpool doesn't support it -- only used during migrations
connect_timeout = 5  # 5 is the default but the migrations runner requires it to be specified

[debug]
cache_game_list_from_api = true
cache_games_from_api = true

[debug.databases.mmoldb]
url = "postgres://postgres:postgres@db/mmoldb"
max_connections = 20  # deadpool doesn't support it -- only used during migrations
connect_timeout = 5  # 5 is the default but the migrations runner requires it to be specified
