[default]
port = 42424  # Must match the port forwarded in .devcontainer/devcontainer.json
log_level = "normal"

[default.databases.mmoldb]
url = "NOTE: This URL will be overridden by one computed from postgres' environment variables"
pool_size = 20
timeout = 5

[debug]
start_ingest_every_launch = true
reimport_all_games = true

[debug.databases.mmoldb]
url = "NOTE: This URL will be overridden by one computed from postgres' environment variables"
pool_size = 20
timeout = 5
