volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
        - .env

    ports:
      - "42424:42424"
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
