volumes:
  http-cache:
  postgres-data-v2:

services:
  app:
#    image: mcr.microsoft.com/devcontainers/rust:2-1-trixie
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - http-cache:${HTTP_CACHE_DIR}
    env_file:
        - .env

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    # docker default is very low
    shm_size: 1gb
    volumes:
      - postgres-data-v2:/var/lib/postgresql/data
        # This is different to the config file path in docker-prod and I have no fuckin clue why.
        # But I checked with `show config_file;` and it does appear to be right
      - ./pg_conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
