display_order = 1
description = """
Contains categorical information. You can think of each `taxa` table as
an enum, and each row as a variant of that enum. The difference between
`taxa` and an actual enum is that `taxa` tables have extra columns with
properties about the variants.

The correct way to use any column that references a `taxa` is to join
on said `taxa` table and use the taxa's `name` in your `where` and
`group by` clauses. However, I recognize that I won't be able to stop
people from using IDs instead, so those are guaranteed to be stable.
"""

[[table]]
name = "event_type"
description = """
The outcome of the pitch (or lack of pitch, in the case of a balk).
The types are very granular to facilitate grouping them in as many
ways as possible. Some common ways to group events are provided by
the many boolean `is_*` columns.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID for an event type. When this appears as a foreign key
you are encouraged to join this `taxa` and use its `name` column,
rather than directly using event type ids in your queries or results.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this event type. Guaranteed to contain
alphanumeric characters only and start with a letter.
"""

[[table.column]]
name = "display_name"
type = "text"
description = """
The human-friendly name for this event type.
"""

[[table.column]]
name = "ends_plate_appearance"
type = "boolean"
description = """
Does an event of this type end the current plate appearance?
"""

[[table.column]]
name = "is_in_play"
type = "boolean"
description = """
Does an event of this type result in a ball in play?
"""

[[table.column]]
name = "is_hit"
type = "boolean"
description = """
Does an event of this type count as a hit, for the purposes of batter
statistics?
"""

[[table.column]]
name = "is_ball"
type = "boolean"
description = """
Does an event of this type represent a pitch outside the strike zone on
which the batter did not swing?
"""

[[table.column]]
name = "is_strike"
type = "boolean"
description = """
Does an event of this type represent either a pitch inside the strike
zone or a pitch on which the batter swung?
"""

[[table.column]]
name = "is_strikeout"
type = "boolean"
description = """
Does an event of this type count as a strikeout, for the purposes of
pitcher statistics?
"""

[[table.column]]
name = "is_basic_strike"
type = "boolean"
description = """
Does an event of this type count as either a strikeout or a
non-PA-ending strike?
"""

[[table.column]]
name = "is_foul"
type = "boolean"
description = """
Does an event of this type count as a foul ball or foul tip?
"""

[[table.column]]
name = "is_foul_tip"
type = "boolean"
description = """
Does an event of this type count as a foul tip?
"""

[[table.column]]
name = "batter_swung"
type = "boolean"
description = """
Does an event of this type represent a pitch on which the batter swung?
"""

[[table]]
name = "fielder_location"
description = """
A location on the field, identified by its associated fielder position.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
The standard baseball fielder number. 1 = pitcher, 2 = catcher, etc.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this fielder location. Guaranteed to contain
alphanumeric characters only and start with a letter.
"""

[[table.column]]
name = "display_name"
type = "text"
description = """
The human-friendly name for this fielder location.
"""

[[table.column]]
name = "abbreviation"
type = "text"
description = """
The standard one- or two-letter abbreviation for this fielder location.
"""

[[table.column]]
name = "area"
type = "text"
description = """
`'Infield'` or `'Outfield'`
"""

[[table]]
name = "fair_ball_type"
description = """
The characterization of a batted ball's trajectory.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID for a fair ball type. When this appears as a foreign
key you are encouraged to join this `taxa` and use its `name` column,
rather than directly using fair ball type ids in your queries or
results.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this fair ball type. Guaranteed to contain
alphanumeric characters only and start with a letter.
"""

[[table.column]]
name = "display_name"
type = "text"
description = """
The human-friendly name for this fair ball type.
"""

[[table]]
name = "slot"
description = """
A possibly-approximate player slot in the roster.

MMOLB has been inconsistent in the past with how it identifies pitchers
who field a ball. At different times (and in different events) they
have been identified just as the pitcher ("P"), as the type of pitcher
(e.g. "SP"), and with their full roster slot identification (e.g.
"SP3"). We do the best we can to provide the most specific
identification available.

Note that because of this MMOLB inconsistency, a position player who is
currently pitching may be identified as "Pitcher" or as their assigned
roster slot.

Eventually we plan to reference other sources to accurately determine
the player's roster slot, at which time the approximate values will be
removed from this `taxa`.

Approximate slots will also be used in case there is a pitcher with a
higher slot than expected, e.g. "SP6" or "RP4". There are no instances
of this as of this writing (at the end of Season 2).
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
The slot's ordinal position on the MMOLB team page, for concrete slots.
For approximate slots (see the table description) this is an arbitrary
number.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this slot. Guaranteed to contain
alphanumeric characters only and start with a letter.
"""

[[table.column]]
name = "display_name"
type = "text"
description = """
The human-friendly name for this slot.
"""

[[table.column]]
name = "abbreviation"
type = "text"
description = """
The standard abbreviation for this slot, as seen on the MMOLB team
page.
"""

[[table.column]]
name = "role"
type = "text"
description = """
`'Pitcher'` or `'Batter'`. NOTE: Players in a batting slot who are
currently pitching may have either value. See the table description
for details.
"""

[[table.column]]
name = "pitcher_type"
type = "text"
description = """
For pitching slots, `'Starter'`, `'Reliever'`, `'Closer'`, or
`'Unknown'`. `'Unknown'` indicates this is a pitcher, but we don't know
which type.
"""
nullable_explanation = """
`null` for non-pitching slots.
"""

[[table.column]]
name = "slot_number"
type = "integer"
description = """
The slot number, if any (1 for SP1, 2 for SP2, etc.). You typically
won't need to use this column, since it's already baked into the slot's
name and abbreviation. It's provided in case it's ever convenient to
manipulate a slot number numerically.
"""
nullable_explanation = """
`null` for non-numbered slots (anything besides Starter and Reliever).
"""

[[table.column]]
name = "location"
type = "bigint"
description = """
The fielder location where this slot typically plays, if applicable.
This is a foreign key into `taxa.fielder_location`.

WARNING: a player in a batting slot who is currently pitching may be
recorded as occupying their batting slot or the Pitcher approximate
slot, meaning their location may be recorded as Pitcher or as their
typical fielder location. See the table description for details.
"""
nullable_explanation = """
`null` for the Designated Hitter.
"""

[[table]]
name = "base"
description = """
A base. Like from baseball.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
The base number. Note that Home is base number 0. There is (currently)
no base number 4.

This numbering was chosen to accommodate potential additional bases.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this base. Guaranteed to contain alphanumeric
characters only and start with a letter.

This is (currently) also the human-friendly name for this base.
"""

[[table.column]]
name = "bases_achieved"
type = "integer"
description = """
The number of bases the player has to advance to end up on this base.
Equal to the base id for every base other than Home.

This column will be deleted if additional bases are ever added to
MMOLB. A new column will be added (not necessarily to this schema) to
record the total number of bases.
"""

[[table]]
name = "base_description_format"
description = """
MMOLB occasionally describes bases in different formats. The same base
may be described as "first", "first base", or "1st". This records which
format was used for a particular description.

This taxa only exists for the purpose of exactly recreating game event
messages from the database (aka "round-tripping"). If you find a
genuine use for it in MMOLB analysis please let us know!
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID for a base description format. When this appears as a
foreign key you are encouraged to join this `taxa` and use its `name`
column, rather than directly using base description format ids in your
queries or results.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this base description format. Guaranteed to
contain alphanumeric characters only and start with a letter.
"""

[[table]]
name = "fielding_error_type"
description = """
The type of a fielding error: throwing or catching.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID for a fielding error type. When this appears as a
foreign key you are encouraged to join this `taxa` and use its `name`
column, rather than directly using fielding error type ids in your
queries or results.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this base description format. Guaranteed to
contain alphanumeric characters only and start with a letter.

This is (currently) also the human-friendly name.
"""


[[table]]
name = "pitch_type"
description = """
Pitch type, as described by the pitch information at the right side of
a pitch event.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID for a pitch type. When this appears as a
foreign key you are encouraged to join this `taxa` and use its `name`
column, rather than directly using fielding error type ids in your
queries or results.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The code-friendly name for this pitch type. Guaranteed to contain
alphanumeric characters only and start with a letter.
"""

[[table.column]]
name = "display_name"
type = "text"
description = """
The human-friendly name for this pitch type.
"""

[[table.column]]
name = "abbreviation"
type = "text"
description = """
The standard baseball abbreviation for this pitch type.
"""

[[table]]
name = "leagues"
description = """
The leagues of MMOLB, both greater and lesser.

These leagues are hard-coded. In future this taxa will be replaced with
a `data.leagues` table which is populated dynamically from MMOLB.

This is currently not referenced in any other tables. We know it would
be desired, but it will take significant work to get there.
"""

[[table.column]]
name = "id"
type = "bigint"
description = """
An arbitrary ID number for a league.
"""

[[table.column]]
name = "name"
type = "text"
description = """
The league's name.
"""

[[table.column]]
name = "color"
type = "text"
description = """
The league's background color as shown on the MMOLB lesser league page.
Greater league teams also have background colors in the API.
"""

[[table.column]]
name = "emoji"
type = "text"
description = """
The league's emoji.
"""

[[table.column]]
name = "league_type"
type = "text"
description = """
`'Greater'` or `'Lesser'`.
"""

[[table.column]]
name = "parent_team_id"
type = "text"
description = """
The MMOLB team id for the league's parent team. For Lesser League teams,
this is the Greater League team they're associated with. For Greater
League teams, this is the league's Superstar team.
"""

[[table.column]]
name = "mmolb_league_id"
type = "text"
description = """
The MMOLB id for the league itself.
"""
